### ISSUE TITLE
Update to phinx 0.8

### ISSUE THREAD

**Issue by lunetics** [ekapusta/doctrine-phinx-bridge-bundle#1]
Is that possible? just started out with phinx.. would love to use it

**Comment by garex** [comment]
@lunetics I think we can even put there just '*'. But any phinx version below 1.0.0 will work.

We use currently "^0.6.4", which permits phinx 0.8. You just need to require phinx 0.8 in your app.

Read more here: https://getcomposer.org/doc/articles/versions.md#caret

**Comment by lunetics** [comment]
Actually not

"For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0."

```
  Problem 1
    - ekapusta/doctrine-phinx-bridge-bundle 1.0.1 requires robmorgan/phinx ^0.6.4 -> satisfiable by robmorgan/phinx[v0.6.4, v0.6.5, v0.6.6] but these conflict with your requirements or minimum-stability.
    - ekapusta/doctrine-phinx-bridge-bundle 1.0 requires robmorgan/phinx ^0.6.4 -> satisfiable by robmorgan/phinx[v0.6.4, v0.6.5, v0.6.6] but these conflict with your requirements or minimum-stability.
    - Installation request for ekapusta/doctrine-phinx-bridge-bundle ^1.0 -> satisfiable by ekapusta/doctrine-phinx-bridge-bundle[1.0, 1.0.1].
```

**Comment by garex** [comment]
What do you suggest then?

https://semver.mwl.be/#?package=robmorgan%2Fphinx&version=%3E%3D0.6.4&minimum-stability=stable

?

**Comment by lunetics** [comment]
"~0.6" or ">=0.6.4 <1.0" will suffice (allowing everything up to <1.x). Ofc you need to keep an eye on backword incompatible changes, they can happen on pre 1.0 versions in minor changes.

**Comment by garex** [comment]
> "~0.6" or ">=0.6.4 <1.0" will suffice (allowing everything up to <1.x).

Ok, let's stick on 0.6.

> Ofc you need to keep an eye on backword incompatible changes, they can happen on pre 1.0 versions in minor changes.

If something fail -- someone will tell us.
